main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('cards/', views.cards_index, name='index'),
    path('cards/<int:card_id>/', views.cards_detail, name='detail'),
    path('cards/create/', views.CardCreate.as_view(), name='cards_create'),
    path('cards/<int:pk>/update/', views.CardUpdate.as_view(), name='cards_update'),
    path('cards/<int:pk>/delete/', views.CardDelete.as_view(), name='cards_delete'),
    path('cards/<int:card_id>/add_priceupdate/', views.add_priceupdate, name='add_priceupdate'),
    path('cards/<int:card_id>/add_photo/', views.add_photo, name='add_photo'),
    path('decks/', views.DeckList.as_view(), name='decks_index'),
    path('decks/<int:pk>/', views.DeckDetail.as_view(), name='decks_detail'),
    path('decks/create/', views.DeckCreate.as_view(), name='decks_create'),
    path('decks/<int:pk>/update/', views.DeckUpdate.as_view(), name='decks_update'),
    path('decks/<int:pk>/delete/', views.DeckDelete.as_view(), name='decks_delete'),
    path('cards/<int:card_id>/assoc_deck/<int:deck_id>/', views.assoc_deck, name='assoc_deck'),
    path('cards/<int:card_id>/unassoc_deck/<int:deck_id>/', views.unassoc_deck, name='unassoc_deck')
    
]

pokemoncollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse

RARITY = (
    ("Common", "C"),
    ("Uncommon", "U"),
    ("Rare", "R"),
    ("Double Rare", "RR"),
    ("Triple Rare", "RRR"),
    ("Super Rare", "SR"),
    ("Special Art", "SIR"),
    ("Hyper Rare", "HR"),
    ("Ultra Rare", "UR"),
    ("Shiny Super Rare", "SSR"),
    ("Shiny", "S"),
    ("Character Rare", "CHR"),
    ("Character Super Rare", "CSR"),
    ("Amazing Rare", "A"),
    ("Radiant Rare", "K"),
)

GRADES = (
    ("UG", "Ungraded"),
    ("1", "PSA 1"),
    ("2", "PSA 2"),
    ("3", "PSA 3"),
    ("4", "PSA 4"),
    ("5", "PSA 5"),
    ("6", "PSA 6"),
    ("7", "PSA 7"),
    ("8", "PSA 8"),
    ("9", "PSA 9"),
    ("10", "PSA 10"),
)

class Deck(models.Model):
  name = models.CharField(max_length=50)
  description = models.TextField(max_length=250)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('decks_detail', kwargs={'pk': self.id})

# Create your models here.
class Card(models.Model):
    name = models.CharField(max_length=100)
    number = models.IntegerField()
    rarity = models.CharField(
        max_length=25,
        choices=RARITY,
        default=RARITY[0][0]
        )
    set = models.CharField(max_length=100)
    decks = models.ManyToManyField(Deck)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'card_id': self.id})
    
class PriceUpdate(models.Model):
  date = models.DateField('Priced Date')
  grade = models.CharField(
      max_length=2,
      choices=GRADES,
      default=GRADES[0][0]
  )
  price = models.IntegerField()
  card = models.ForeignKey(Card, on_delete=models.CASCADE)

#   def __str__(self):
#     # Nice method for obtaining the friendly value of a Field.choice
#     return f"{self.get_priceupdate_display()} on {self.date}"
  
class Photo(models.Model):
    url = models.CharField(max_length=200)
    card = models.ForeignKey(Card, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for card_id: {self.card_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import PriceUpdate

class PriceUpdateForm(ModelForm):
  class Meta:
    model = PriceUpdate
    fields = ['date', 'grade', 'price']

main_app/views.py
import uuid
import boto3
import os

from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django import forms
from .forms import PriceUpdateForm

from .models import Card, Deck, Photo

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def cards_index(request):
    cards = Card.objects.all()
    return render(request, 'cards/index.html', {
        'cards': cards
    })

def add_photo(request, card_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            # build the full url string
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            # we can assign to cat_id or cat (if you have a cat object)
            Photo.objects.create(url=url, card_id=card_id)
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
    return redirect('detail', card_id=card_id)

def cards_detail(request, card_id):
    card = Card.objects.get(id=card_id)
    id_list = card.decks.all().values_list('id')
    decks_card_doesnt_have = Deck.objects.exclude(id__in=id_list)
    priceupdate_form = PriceUpdateForm()
    return render(request, 'cards/detail.html', { 
        'card': card, 'priceupdate_form': priceupdate_form, 'decks': decks_card_doesnt_have })

def add_priceupdate(request, card_id):
    form = PriceUpdateForm(request.POST)
    if form.is_valid():
        new_priceupdate = form.save(commit=False)
        new_priceupdate.card_id = card_id
        new_priceupdate.save()
    return redirect('detail', card_id=card_id)

class DeckList(ListView):
  model = Deck

class DeckDetail(DetailView):
  model = Deck

class DeckCreate(CreateView):
  model = Deck
  fields = '__all__'

class DeckUpdate(UpdateView):
  model = Deck
  fields = ['name', 'description']

class DeckDelete(DeleteView):
  model = Deck
  success_url = '/decks'

def assoc_deck(request, card_id, deck_id):
    Card.objects.get(id=card_id).decks.add(deck_id)
    return redirect('detail', card_id=card_id)

def unassoc_deck(request, card_id, deck_id):
    Card.objects.get(id=card_id).decks.remove(deck_id)
    return redirect('detail', card_id=card_id)

class CardCreate(CreateView):
    model = Card
    fields = ['name', 'number', 'rarity', 'set']
    success_url = '/cards'

class CardUpdate(UpdateView):
    model = Card
    fields = ['name', 'number', 'rarity', 'set']

class CardDelete(DeleteView):
    model = Card
    success_url = '/cards'

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}
<h1>About the Pokemon Collector</h1>
<hr />
<p>Buy some cards!</p>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Card Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="/" class="left brand-logo"
                >&nbsp;&nbsp;Pokemon Collector</a
              >
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'decks_create' %}">Add a Deck</a></li>
            <li><a href="{% url 'decks_index' %}">View All Decks</a></li>
            <li><a href="{% url 'cards_create' %}">Add a Card</a></li>
            <li><a href="{% url 'index' %}">View All Cards</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">
        All Rights Reserved, &copy; 2021 Poke Collector &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/cards/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Card Details</h1>
<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ card.name }}</span>
        <p>({{ card.set }})</p>
        {% for photo in card.photo_set.all %}
          <img class="responsive-img card-panel" src="{{photo.url}}">
        {% empty %}
          <div class="card-panel teal-text center-align">No Photos Uploaded</div>
          <form action="{% url 'add_photo' card.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
            {% csrf_token %}
            <input type="file" name="photo-file">
            <br><br>
            <button type="submit" class="btn">Upload Photo</button>
        </form>
        {% endfor %}
        <p>Rarity: {{ card.rarity }}</p>
        <p>Card Number: {{ card.number }}</p>
        <!-- <p>Price (Ungraded): ${{ card.price_ungraded }}</p>
        <p>Price (PSA 10): ${{ card.price_psa10 }}</p> -->
      </div>
    </div>
    <div class="card-action">
      <a href="{% url 'cards_update' card.id %}">Edit</a>
      <a href="{% url 'cards_delete' card.id %}">Delete</a>
    </div>
  </div>
</div>
<div class="col s6">
  <form action="{% url 'add_priceupdate' card.id %}" method="POST">
    {% csrf_token %} {{ priceupdate_form.as_p }}
    <input type="submit" class="btn" value="Add Price" />
  </form>
  <table class="striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>PSA Grading</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      {% for priceupdate in card.priceupdate_set.all %}
      <tr>
        <td>{{priceupdate.date}}</td>
        <td>{{priceupdate.grade}}</td>
        <td>${{priceupdate.price}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<hr />
<div class="row">
  <div class="col s6">
    <h3>Decks with {{ card.name }}</h3>
    {% if card.decks.count %} {% for deck in card.decks.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title"> {{ deck.name }} </span>
      </div>
      <div class="card-action">
        <form action="{% url 'unassoc_deck' card.id deck.id %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn">REMOVE</button>
        </form>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>No Current Decks</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Decks</h3>
    {% if decks.count %}
      {% for deck in decks.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              {{ deck.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_deck' card.id deck.id %}" method="POST">
                {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{card.name}} is in all current decks</h5>
    {% endif %}
  </div>
</div>
<script>
  const dateEl = document.getElementById("id_date");
  // M is Materialize's global variable
  M.Datepicker.init(dateEl, {
    format: "yyyy-mm-dd",
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  });

  const selectEl = document.getElementById("id_grade");
  M.FormSelect.init(selectEl);

</script>
{% endblock %}

main_app/templates/cards/index.html
{% extends 'base.html' %} {% block content %}

<h1>Card List</h1>

{% for card in cards %}
<div class="card">
  <a href="{% url 'detail' card.id %}">
    <div class="card-content">
      <span class="card-title">{{ card.name }}</span>
    </a>
    </div>
</div>
{% endfor %} {% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}
<h1>Home</h1>
{% endblock %}

main_app/templates/main_app/card_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Card</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete" class="btn" />
  <a href="{% url 'detail' card.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/card_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Card</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="POST">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>

<script>
  const selectEl = document.getElementById("id_rarity");
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/main_app/deck_detail.html
{% extends 'base.html' %} {% block content %}

<h1>Deck Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ deck.name }}</span>
        <p>Description: {{ deck.description }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'decks_update' deck.id %}">Edit</a>
        <a href="{% url 'decks_delete' deck.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/deck_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Deck</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/main_app/deck_list.html
{% extends 'base.html' %} {% block content %}

<h1>Deck List</h1>

{% for deck in deck_list %}
<a href="{% url 'decks_detail' deck.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ deck.name }}</span>
      <p>Description: {{ deck.description }}</p>
    </div>
  </div>
</a>
{% endfor %} {% endblock %}